options:
  logging: CLOUD_LOGGING_ONLY
  # Or use "NONE" if you don't want logs
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'taxgpt-database', '--zone', 'us-central1-f', '--command', 'bash -s', '--', '<', './deploy.sh']
  id: Deploy to VM

images:
- 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA'
