steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/taxGPT-database/taxgpt-database-image:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/taxGPT-database/taxgpt-database-image:$SHORT_SHA']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/taxGPT-database/taxgpt-database-image:$SHORT_SHA'
