options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'python:3.10'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      python -m pip install --upgrade pip setuptools
  id: Install setuptools in Build environment
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:latest', '.']
  id: Creating a new image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA']
  id: Pushing updated image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:latest']
  id: Pushing updated image to latest tag
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - instances
  - add-metadata
  - taxgpt-database  
  - --zone=us-central1-f 
  - --metadata-from-file=gce-container-declaration=./container.yaml
  id: Update container manifest and startup script
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instances update-container taxgpt-database --zone=us-central1-f --container-image gcr.io/taxgpt-413814/taxgpt-database-image:latest
  id: Update the container image on the VM
images:
- 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA'