options:
  logging: CLOUD_LOGGING_ONLY
  # Or use "NONE" if you don't want logs
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA']

images:
- 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA'

