#cloud-config
runcmd:
  - |
    mkdir -p /etc/taxgpt_database_env
    ACCESS_TOKEN=$(curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" -H "Metadata-Flavor: Google" -s | jq -r '.access_token')
    SECRET_VALUE=$(curl "https://secretmanager.googleapis.com/v1/projects/YOUR_PROJECT_ID/secrets/taxgpt-database-env/versions/latest:access" -H "Authorization: Bearer ${ACCESS_TOKEN}" -s | jq -r '.payload.data' | base64 --decode)
    echo "${SECRET_VALUE}" >> /etc/taxgpt_database_env/.env