options:
  logging: CLOUD_LOGGING_ONLY
steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if ! gcloud secrets describe taxgpt-database-env --project=$PROJECT_ID; then
      gcloud secrets create taxgpt-database-env --replication-policy="automatic" --project=$PROJECT_ID
    fi
  id: Creating the secret if it does not exist
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['secrets', 'versions', 'add', 'taxgpt-database-env', '--data-file', '.env']
  id: Updating the secret with the content of the .env file

# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     gcloud secrets versions access latest --secret=taxgpt-database-env > .taxgpt_database_env
#     gsutil cp .taxgpt_database_env gs://taxgpt-database-storage/.taxgpt_database_env
#   id: Copying environment variables from secret manager
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:latest', '.']
  id: Creating a new image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA']
  id: Pushing updated image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:latest']
  id: Pushing updated image to latest tag
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - instances
  - add-metadata
  - taxgpt-database  
  - --zone=us-central1-f 
  - --metadata-from-file=gce-container-declaration=./container.yaml,user-data=./cloud-init.yaml
  id: Update container manifest and startup script
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instances update-container taxgpt-database --zone=us-central1-f --container-image gcr.io/taxgpt-413814/taxgpt-database-image:latest
  id: Update the container image on the VM
images:
- 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA'