options:
  logging: CLOUD_LOGGING_ONLY
  # Or use "NONE" if you don't want logs
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA', '.']
  id: Creating a new image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA']
  id: Pushing updated image to Google Container Registry
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export HOME=/workspace
    mkdir -p $HOME/.ssh
    echo "$$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
    chmod 600 $HOME/.ssh/id_rsa
    gcloud compute ssh taxgpt-database --zone us-central1-f --command "bash -s" -- < ./deploy.sh
  secretEnv: ['SSH_PRIVATE_KEY']
  id: Deploy to VM

images:
- 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA'


secrets:
- kmsKeyName: ''  # Not using Cloud KMS, so this is left empty.
  secretEnv:
    SSH_PRIVATE_KEY: projects/$PROJECT_ID/secrets/cloud-build-taxgpt-database-key/versions/latest