options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA', '.']
  id: Creating a new image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA']
  id: Pushing updated image to Google Container Registry
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export home=/workspace 
    mkdir -p $home/.ssh 
    gcloud secrets versions access latest --secret=cloud-build-taxgpt-database-key > $home/.ssh/id_rsa 
    cat $home/.ssh/id_rsa
    chmod 600 $home/.ssh/id_rsa 
    gcloud compute ssh taxgpt-database --ssh-flag="-i $home/.ssh/id_rsa" --zone us-central1-f --command "bash -s" -- < ./deploy.sh
  # secretEnv: ['SSH_PRIVATE_KEY']
  id: Deploy to VM

images:
- 'gcr.io/$PROJECT_ID/taxgpt-database-image:$SHORT_SHA'

# availableSecrets:
#   secretManager:
#   - versionName: rojects/$PROJECT_ID/secrets/cloud-build-taxgpt-database-key/versions/latest
#     env: 'SSH_PRIVATE_KEY'
    